server {
    listen 80;
    server_name _;

    location /admin/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /admin/index.html;
    }

    location /teacher/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /teacher/index.html;
    }
}
