-- 20251029170000_initial_schema.sql

-- 1. جدول المعلمين (المستخدمين)
-- يستخدم جدول 'auth.users' من Supabase مباشرة للمصادقة.
-- هذا الجدول يخزن البيانات الإضافية للمعلم.
CREATE TABLE public.teachers (
    id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
    full_name text,
    created_at timestamp with time zone DEFAULT now()
);

-- تمكين Row Level Security (RLS)
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;

-- السماح للمعلم برؤية وتعديل بياناته فقط
CREATE POLICY "Teachers can view and update their own profile" ON public.teachers
    FOR ALL USING (auth.uid() = id);


-- 2. جدول الفصول الدراسية
CREATE TABLE public.classes (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    teacher_id uuid REFERENCES public.teachers(id) NOT NULL,
    class_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- تمكين RLS
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

-- السماح للمعلم برؤية وتعديل فصوله فقط
CREATE POLICY "Teachers can manage their own classes" ON public.classes
    FOR ALL USING (auth.uid() = teacher_id);


-- 3. جدول الطلاب
CREATE TABLE public.students (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    class_id uuid REFERENCES public.classes(id) NOT NULL,
    student_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- تمكين RLS
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- السماح للمعلم برؤية وتعديل طلابه فقط (عبر الفصول التي يملكها)
CREATE POLICY "Teachers can manage students in their classes" ON public.students
    FOR ALL USING (
        (SELECT teacher_id FROM public.classes WHERE id = class_id) = auth.uid()
    );


-- 4. جدول سجل الأداء اليومي (للحضور، الواجبات، المشاركة، السلوك)
CREATE TABLE public.performance_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id uuid REFERENCES public.students(id) NOT NULL,
    log_date date DEFAULT now() NOT NULL,
    log_type text NOT NULL, -- 'attendance', 'participation', 'homework', 'behavior'
    points_awarded integer DEFAULT 0,
    behavior_note text, -- للملاحظات السلوكية
    homework_title text, -- لعنوان الواجب
    created_at timestamp with time zone DEFAULT now()
);

-- تمكين RLS
ALTER TABLE public.performance_log ENABLE ROW LEVEL SECURITY;

-- السماح للمعلم برؤية وتعديل سجلات طلابه فقط
CREATE POLICY "Teachers can manage their students' performance log" ON public.performance_log
    FOR ALL USING (
        (SELECT teacher_id FROM public.classes WHERE id = (SELECT class_id FROM public.students WHERE id = student_id)) = auth.uid()
    );


-- 5. جدول إعدادات النقاط (لتخصيص المعلم)
CREATE TABLE public.point_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id uuid REFERENCES public.teachers(id) NOT NULL,
    setting_key text NOT NULL, -- 'attendance_points', 'participation_points', 'negative_behavior_points'
    setting_value integer NOT NULL,
    CONSTRAINT unique_teacher_setting UNIQUE (teacher_id, setting_key)
);

-- تمكين RLS
ALTER TABLE public.point_settings ENABLE ROW LEVEL SECURITY;

-- السماح للمعلم برؤية وتعديل إعدادات نقاطه فقط
CREATE POLICY "Teachers can manage their own point settings" ON public.point_settings
    FOR ALL USING (auth.uid() = teacher_id);


-- 6. جدول الاشتراكات (لإدارة المالك)
-- هذا الجدول لا يخضع لـ RLS لأنه خاص بالمالك فقط (Super Admin)
CREATE TABLE public.subscriptions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    teacher_id uuid REFERENCES public.teachers(id) NOT NULL,
    plan_name text NOT NULL,
    start_date date DEFAULT now() NOT NULL,
    end_date date,
    is_active boolean DEFAULT TRUE
);

-- لا يتم تمكين RLS على هذا الجدول، بل يتم التحكم في الوصول إليه عبر واجهة برمجة تطبيقات خاصة بالمالك.

-- 7. جدول الخطط (لإدارة المالك)
CREATE TABLE public.plans (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    plan_name text NOT NULL,
    monthly_price numeric,
    yearly_price numeric,
    max_classes integer,
    max_students_per_class integer,
    can_export_excel boolean,
    is_active boolean DEFAULT TRUE
);

-- لا يتم تمكين RLS على هذا الجدول، بل يتم التحكم في الوصول إليه عبر واجهة برمجة تطبيقات خاصة بالمالك.
