name: Build Flutter APK

on:
  push:
    branches:
      - final-delivery
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # أو أحدث إصدار تبيه

      - name: Get dependencies
        working-directory: teacher_app
        run: flutter pub get

      - name: Build release APK
        working-directory: teacher_app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: teacher_app-release-apk
          path: teacher_app/build/app/outputs/flutter-apk/app-release.apk
